using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Padi.SharedModel;
using System.Runtime.Remoting.Channels.Tcp;
using System.Runtime.Remoting.Channels;
using System.Runtime.Remoting;

namespace Padi.User
{
    public class Client : MarshalByRefObject, IClient
    {
        //URL of the worker node used to submit jobs
        private string entryURL;

        //Job dictionary
        private Dictionary<string, Job> jobs = new Dictionary<string, Job>();

        public Client(string EntryURL)
        {
            this.entryURL = EntryURL;
        }


        public void Submit(string inputPath, string outputPath, int splits, string className, string dllPath)
        {

            //TODO: Invoke splitFile and submit the job to the node in "entryURL".
        }

        private void splitFile(string inputPath)
        {
            //TODO: Implement the split function and save the data to the jobs dictionary
        }

        // Return a split of the input file to a worker node
        public /*IList<KeyValuePair<string, string>>*/void returnSplit(string jobName, string splitNumber)
        {



        }

        // Obtains the results generated by the processing of a split from a worker node
        public void obtainResults()
        {

        }
    }

    class Job
    {
        //TODO: This class should maintain a list of KeyValuePairs containing the file splits for this job
    }
}
